# Site settings
title: Ripple Networks
email: press@ripplenetworks.com
description: Ripple Networks provides the highest quality consumer experience for globally distributed video and data over the internet.
baseurl: "/ripple-jekyll/" # the subpath of your site, e.g. /blog/
url: "http://ripplenetworks.com" # the base hostname & protocol for your site
twitter_username: ripplenetworks
facebook_username: ripplenetworks

# Build settings
markdown: kramdown
